VERBS = {
    "Push aside",
    "Relegate",
    "Forget",
    "Sidestep",
    "Spurn",
    "Evince disinterest in",
    "Brush aside",
    "Ignore",
    "Disown",
    "Disavow",
    "Rebuff",
    "Disparage",
    "Decry",
    "Eschew",
    "Turn one's back on",
    "Fail to notice",
    "Abandon",
    "Forgo",
    "Dismiss",
    "Decline",
    "Slight",
    "Exclude",
    "Downplay",
    "Cold-shoulder",
    "Omit",
    "Overlook",
    "Give the cold shoulder",
    "Withdraw from",
    "Neglect",
    "Slip by",
    "Diminish",
    "Do not follow",
    "Forsake",
    "Duck",
    "Pay no attention to",
    "Skip",
    "Shrug off",
    "Refuse to acknowledge",
    "Shut eyes to",
    "Reject",
    "Do not obey",
    "Disobey",
    "Pass by",
    "Avoid",
    "Look past",
    "Elude",
    "Discredit",
    "Evade",
    "Devalue",
    "Ridicule",
    "Close ears to",
    "Leave out",
    "Deflect",
    "Negate",
    "Mock",
    "Underestimate",
    "Deride",
    "Cast aside",
    "Disregard",
    "Pass over",
    "Scorn",
    "Repudiate",
    "Bypass",
    "Snub",
    "Underplay",
    "Cut out",
    "Renounce",
    "Wave aside",
    "Turn a blind eye to",
    "Disclaim",
    "Disaffirm",
    "Tune out",
    "Belittle",
    "Look away from",
    "Ignore completely",
    "Turn away from",
    "Overlook intentionally",
    "Brush off",
    "Neglect to mention",
    "Forget about",
    "Dismiss out of hand",
    "Cast off",
    "Turn down",
    "Disregard entirely",
    "Overlook deliberately",
    "Discount",
    "Pass up",
    "Write off",
    "Let go",
    "Turn aside",
    "Shun",
    "Refrain from noticing",
    "Turn a deaf ear to",
    "Bypass intentionally",
    "Abstain from acknowledging",
    "Push away",
    "Repel",
    "Look the other way",
    "Repel attention from",
    "Close eyes to",
    "Shut out",
    "Ignore outright",
    "Steer clear of",
    "Turn one's face from",
    "Look beyond",
    "Snub intentionally",
    "Turn a blind eye",
    "Refuse to consider",
    "Dismiss as irrelevant",
    "Set aside",
    "Avoid completely",
    "Cut off",
    "Ignore on purpose",
    "Brush aside casually",
    "Disregard as unimportant",
    "Wave off",
    "Discount as trivial",
    "Dismiss without consideration",
    "Ignore as inconsequential",
    "Sideline",
    "Overlook as insignificant",
    "Disregard with intent",
    "Write off as unimportant",
    "Pass by unnoticed",
    "Turn one's head from",
    "Neglect to consider",
    "Disown emotionally",
    "Diminish importance of",
    "Turn back on",
    "Disown responsibility for",
    "Dismiss outright",
    "Push away from mind",
    "Repudiate attention to",
    "Cast off mentally",
    "Fail to acknowledge",
    "Shut mind to",
    "Overlook by choice",
    "Discount mentally",
    "Turn one's focus away",
    "Refuse mentally",
    "Ignore by default",
    "Neglect mentally",
    "Turn thoughts away",
    "Neglect purposefully",
    "Ignore totally",
    "Sidestep mentally",
    "Disregard intentionally",
    "Push out of mind",
    "Forget mentally",
    "Diminish mentally",
    "Bypass mentally",
    "Disregard mentally",
    "Set aside mentally",
    "Turn back mentally",
    "Write off mentally",
    "Repudiate mentally",
    "Dismiss mentally",
    "Neglect thought",
    "Ignore thought",
    "Overlook thought",
    "Disregard thought",
    "Set aside thought",
    "Shut out thought",
    "Dismiss thought",
    "Push out thought",
    "Repel thought",
    "Turn thought away",
    "Overlook mental",
    "Disregard mental",
    "Set aside mental",
    "Shut out mental",
    "Dismiss mental",
    "Push out mental",
    "Repel mental",
    "Turn mental away",
    "Overlook mentally",
}